### ISSUE TITLE
warn missing peer some loader..

### ISSUE THREAD

**Issue by leosin** [cpsoinos/nuxt-svgo#101]
![image](https://user-images.githubusercontent.com/3676670/235280560-dbd80e54-299c-41fa-b1b8-e1d40f469d3d.png)
After upgrading from 1.21 to 2.0.1, it still prompts warn missing peer, can I ignore it?

**Comment by jd1378** [comment]
if you are using webpack, you have to install them, if you use vite, yes ignore them :)
