### ISSUE TITLE
Remove default nuxt-icon css classes

### ISSUE THREAD

**Issue by marvinhuebner** [cpsoinos/nuxt-svgo#106]
After upgrading to version 3 (coming from 1), I noticed that a `nuxt-icon` and `nuxt-icon--filled` CSS class is always rendered.

Is there any way to introduce a global option so that I don't have to manually set `:filled="true"` and `:font-controlled="false"` to all components?

Of course I could write myself a wrapper component, but maybe that would be a general improvement of the module?

Thanks in advance.

**Comment by jd1378** [comment]
Try setting 'defaultImport' to 'component'
I think it does what you want and no longer uses nuxt-icon when loading svg

**Comment by marvinhuebner** [comment]
This does work, thanks!

**Comment by KnifeFed** [comment]
Ah, so tree shaking and SSR will work either way then?

**Comment by jd1378** [comment]
yes, as far as I remember it does
