### ISSUE TITLE
plugin for vite that will let use nuxt-svgo in storybook

### ISSUE THREAD

**Issue by mr-tkachuk** [cpsoinos/nuxt-svgo#111]
Guys, may be I accidentally skipped the instructions, how this really useful nuxt-module could be used with storybook.
In my project it works OK - i can see all icons, but in storybook i can see only warning 
"Failed to resolve component: SvgoTrashBin
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement." 

Please, help me find a solution

Thank you so much!

**Comment by jd1378** [comment]
I haven't use storybook in my projects, so I really have no idea
@cpsoinos do you know anything ?

**Comment by cpsoinos** [comment]
@mr-tkachuk you can create a vite config for your Storybook to use that handles auto imports and loading SVGs as Vue components. This article may be helpful: https://laurentcazanove.com/articles/storybook-nuxt-guide/

**Comment by mr-tkachuk** [comment]
@cpsoinos Ty, i've already seen this article and made vite.config with AutoImport and Components Plugins as it recommends. They work pretty efficient with auto import of my components, but auto importing of <SvgoIconName /> still doesn't work. If I undestand correctly, theese plugins requires Custom Resolvers to resolve Components for example from ui libs, or from other source, like nuxt-svgo module.
I'm trying my best to find a solution, but it seems like too difficult for me right now unfortunately

**Comment by cpsoinos** [comment]
Ah ok. I can help figure this out when I return from vacation in a couple of weeks if it's still an issue, but I don't have a computer with me at the moment

**Comment by mr-tkachuk** [comment]
@cpsoinos Oh, it's definitely OK, i wish you a great vacation, and hope to talk to you then!)
I'm very grateful for your answer)

**Comment by mr-tkachuk** [comment]
@cpsoinos hey there)
Are there any news about this issue?

**Comment by cpsoinos** [comment]
@mr-tkachuk I was able to put together an [example repo](https://github.com/cpsoinos/nuxt-svgo-storybook-example) using https://github.com/hirotaka/storybook-addon-nuxt. I followed the instructions in [README.md](https://github.com/hirotaka/storybook-addon-nuxt#readme) and it works out of the box!
