### ISSUE TITLE
Width is overwritten when using Tailwind

### ISSUE THREAD

**Issue by mrleblanc101** [cpsoinos/nuxt-svgo#122]
In the exemple we have this:
`<SvgoHome class="w-5 h-5" />`
In my project I do this:
`<SvgoShowbizz class="w-32" />`
But with the applied style are `width: 1em; height: 1em;` because of the `.nuxt-icon` class.
Is this normal ?
![Capture d’écran, le 2023-06-16 à 02 12 51](https://github.com/cpsoinos/nuxt-svgo/assets/17392251/72f3aeec-1da7-4884-bf53-3e55de03f4c3)

**Comment by jd1378** [comment]
use `:fontControlled="false"`, It will remove those and you can control the width and height without setting font size :)

**Comment by jd1378** [comment]
if you want to change the size without using `fontControlled`, you can simply use `text-2xl` for example to change font size which will make the icon bigger

**Comment by mrleblanc101** [comment]
@jd1378 I think `fontControlled="false"` should be the default.
At least the exemple in the README made me think so.
Mabye the exemple should be updated to make it clearer ?

**Comment by jd1378** [comment]
the default is to load SVGs as icons, and you usually want to size icons relative to your font size, which is why `fontControlled` is `true` by default

if you want to not use the icon component, and size all your components manually, you can simply change this behavior as directed in the readme:
> If you want to use auto import but you don't want to use the nuxt-icon component (used by default), You can do so by using defaultImport: 'component':
```ts
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  modules: ['nuxt-svgo'],
  svgo: {
    defaultImport: 'component' // default is `componentext`
  }
})
```

**Comment by mrleblanc101** [comment]
@jd1378 Then, as I said, the documentation should be update to make this clearer. 
The first exemple use width and height without specifying `fontControlled: false`
![image](https://github.com/cpsoinos/nuxt-svgo/assets/17392251/37bad3a4-72f2-4638-80a6-e4b3856dd5aa)

**Comment by jd1378** [comment]
You are right, I did not realize it until this point
thanks for pointing it out
I'll update the docs
