### ISSUE TITLE
Why only icons?

### ISSUE THREAD

**Issue by frederikheld** [cpsoinos/nuxt-svgo#123]
After reading the docs, I understand that this plugin is made to import SVG files as icon components.

My question is: why only icons? It would be great to use SVG files as illustrations and such.

The only thing that seems to prevents this use case is that the plugin automatically adds the classes `nuxt-icon` and `nuxt-icon--fill` to the `svg` element. If I remove those via the browser dev tools, the SVG is displayed full size and I can change its size via the inline style property on the component:

```vue
<script setup>
import SvgIllustration from '@/assets/img/illustration.svg'
</script>

<template>
    <v-container>
        <v-row>
            <v-col cols="12">
                <SvgIllustration style="width: 240px; height: 240px;" />
            </v-col>
        </v-row>
    </v-container>
</template>
```
Is there any configuration property that removes the icon classes from the generated `svg` element?

**Comment by jd1378** [comment]
yes there is, but I guess you understood it wrong

you can use `:font-controlled="false"` to disable the font controlled width and height
```vue
<SvgIllustration :font-controlled="false" />
```
you can add "filled" attribute to it to use the original illustration color (not the current text color)
```vue
<SvgIllustration :font-controlled="false" filled />
```

you can change the auto import to not use the custom component at all, and simply import the optimized svg ([as mentioned in the docs](https://github.com/cpsoinos/nuxt-svgo/blob/641fb88250adf9b3ea8ab63c05849451977bff27/README.md?plain=1#L85-L97)):
```
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  modules: ['nuxt-svgo'],
  svgo: {
    defaultImport: 'component'
  }
})
```

I hope this helps :)

**Comment by frederikheld** [comment]
Awesome, thanks a lot for your help! I really missed that piece of information. No offense taken ;-)

**Comment by jd1378** [comment]
I'm glad I could help
