### ISSUE TITLE
Import queries not working when using component

### ISSUE THREAD

**Issue by TimWitzdam** [cpsoinos/nuxt-svgo#137]
Hey, I enjoy using the component provided (e.g. <SvgoHome />), but import queries don't seem to work.

Is that something you can add to the documentation or implement into the component?

**Comment by jd1378** [comment]
Hi 
can you explain what you tried , what you expected to happen , and what did not happen ? some code example is appreciated

**Comment by jd1378** [comment]
also mention you use webpack or vite, it only works on vite

**Comment by TimWitzdam** [comment]
Yea sorry, Github seems to have removed what I wrote in brackets. Basically I would like to use something like this:
`<SvgoPhone : skipsvgo=true />`

I'm using Vite and this doesn't seem to work. Imma check out your readme update then, thanks :)

**Comment by jd1378** [comment]
oh import queries are for direct imports, not the component
It's not really possible to achieve that easily
for now you can simply import your `phone.svg` file like this and use it:
```js
import PhoneSvg from "~/your-assets/icons/phone.svg?skipsvgo"
```

**Comment by jd1378** [comment]
also, why would you want to skip svgo for an icon ? just curious what's the use case, maybe there's a problem we can solve another way ?

**Comment by TimWitzdam** [comment]
I resorted direct importing like you showed above.

This svg:
`          <svg
            width="18"
            height="19"
            viewBox="0 0 18 19"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <g clip-path="url(#clip0_654_362)">
              <path
                d="M4.95712 8.1447C5.5621 9.24145 6.25937 10.294 7.16464 11.2539C8.07285 12.2196 9.20224 13.0985 10.6642 13.8493C10.7726 13.9023 10.8751 13.9023 10.9674 13.8655C11.1065 13.8125 11.2486 13.6962 11.3878 13.5563C11.4962 13.4474 11.631 13.2737 11.7716 13.0838C12.3341 12.3403 13.0299 11.4173 14.0128 11.8795C14.0348 11.8899 14.0509 11.9016 14.0728 11.9105L17.3512 13.8051C17.3614 13.811 17.3731 13.8213 17.3819 13.8272C17.8141 14.1261 17.9928 14.5868 17.9972 15.1094C17.9972 15.6409 17.8023 16.2386 17.5167 16.7435C17.1388 17.4104 16.5821 17.8521 15.9405 18.1436C15.3297 18.4262 14.65 18.5778 13.9967 18.675C12.9713 18.8266 12.0103 18.7295 11.0274 18.4262C10.0665 18.1274 9.09824 17.6342 8.04062 16.9776L7.96298 16.9276C7.47812 16.6228 6.95371 16.2975 6.43955 15.9132C4.55869 14.4853 2.64121 12.4228 1.39169 10.1527C0.34433 8.24775 -0.226959 6.19115 0.0850527 4.23172C0.257904 3.15705 0.716401 2.17954 1.51621 1.53474C2.21347 0.969433 3.15244 0.660281 4.36826 0.76922C4.50742 0.779525 4.63193 0.860494 4.69785 0.98121L6.7999 4.55265C7.10751 4.95308 7.1456 5.35056 6.97714 5.74804C6.83798 6.07338 6.55673 6.3737 6.17294 6.65341C6.06015 6.75057 5.92538 6.84921 5.7833 6.95226C5.31308 7.29527 4.77841 7.69128 4.96152 8.15648L4.95712 8.1447Z"
                fill="white"
              />
            </g>
            <defs>
              <clipPath id="clip0_654_362">
                <rect
                  width="18"
                  height="18"
                  fill="white"
                  transform="translate(0 0.74707)"
                />
              </clipPath>
            </defs>
          </svg>`

Is cut off, when I use the optimized version (default config) with the component.

**Comment by jd1378** [comment]
can you send the cut off version as well ?

**Comment by jd1378** [comment]
I see
the default config removes dimensions (width and height) and retains viewBox
if you rely on width and height, then it will get clipped

I'll check the SVG and get back to you for more details

**Comment by TimWitzdam** [comment]
Thanks for the help so far :)

**Comment by jd1378** [comment]
I couldn't find an issue being caused by the nuxt-icon component, so it's probably from something else

aside from that, try to make your icons without ids (`clip0_654_362` here), which means don't use filters and clipPaths and etc unless absolutely necessary, it would cause you headaches later, because duplicate id's cant exist in the dom

**Comment by TimWitzdam** [comment]
Good to know, thanks.
