### ISSUE TITLE
Multiple inline icons break each other due to clip path name clash

### ISSUE THREAD

**Issue by IlyaSemenov** [cpsoinos/nuxt-svgo#139]
### Problem

Multiple inline icons break each other due to clip path name clash.

After optimizing and inlining, icons have the same clip-path URLs such as `<g clip-path="url(#a)">`. The clip path of the first icon clips the other icons.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-gygxiq?file=app.vue

In the reproduction, the sun icon only has the upper left part visible, however if you remove the arrow icon from the template, the sun icon becomes visible fully.

### Suggested fix

The workaround would be to at least enable `prefixIds` svgo plugin by default. Better yet, I think it should be configured to use the hash of the svg path, or some inner sequential ID (to prevent naming clash on the icons with the same file name but in different folders).

**Comment by jd1378** [comment]
I think enabling `prefixIds` is a good idea, as I have it on my own project enabled
I'll look into this as well

**Comment by jd1378** [comment]
do have any hash function in mind that produce small string and low collision rate, and need small dependency or no dependency if possible ?

**Comment by jd1378** [comment]
or just we can use basename (the default) and the sequential ID appended (seems easier)

**Comment by jd1378** [comment]
it was using the same prefix for the entire file, so the sequential id in a function for prefix did not work
using https://stackoverflow.com/a/8831937/3542461 for hashing the whole file path

**Comment by jd1378** [comment]
resolved by #141
