### ISSUE TITLE
[Feature Request] Ability to remove margin on icon components

### ISSUE THREAD

**Issue by madebyfabian** [cpsoinos/nuxt-svgo#144]
Thank you for this module!

I would like to remove/change the margin styles (and propably others) coming from the `.nuxt-icon` class:
![Bildschirm­foto 2023-07-13 um 08 48 33](https://github.com/cpsoinos/nuxt-svgo/assets/32813692/438ff1cc-c171-4f50-8d45-5620ab890cf8)

Is there any possibility without having to do overrides with !important?

**Comment by jd1378** [comment]
Hi
for now you have to use !important to override

but for this feature overall, I'm not really sure how it would be done
one idea that comes to my mind is creating multiple copies of the component with different configurations and load the one according to the module options (this is quite easy but not clean)

one other idea is to build a component from the config and then import that (next to No idea of how to do this)

one other idea is to allow using a custom component instead of `nuxt-icon` (I think this is the best idea)

what do you think ?

**Comment by madebyfabian** [comment]
@jd1378 Yeah I think the ability to use a custom component would be great, since this would really allow to configure everything.

**Comment by jd1378** [comment]
great

please remind me next week if I didn't start working on it till Tuesday , I'm busy at the moment but I will try to make this happen soon :)

**Comment by jd1378** [comment]
@madebyfabian let me know if there's any issue :)

**Comment by madebyfabian** [comment]
@jd1378 Thanks for your work! I cannot get it to run though. Maybe I'm missing something.
- Updated the package to `^3.4.0`
- Removed the `.nuxt` folder and let it regenerate
- Added `svgo.customComponent: 'Icon'` option to `nuxt.config.ts` (TypeScript tells me this method is not available somehow)
- Created a `components/Icon.vue` component, currently exactly copied from your source code.
- Importing Icons like this:
```html
<template>
	<div>
		<!-- Other stuff -->
		<IconArrowRight
			class="text-[28px] text-gray-500 transition-transform group-hover/LayoutJobItem:translate-x-1"
		/>
	</div>
</template>

<script setup lang="ts">
	import IconArrowRight from '@/assets/images/icons/arrowRight.svg'
</script>

```

Though I get the following error:
![Bildschirm­foto 2023-07-19 um 07 08 27](https://github.com/cpsoinos/nuxt-svgo/assets/32813692/7d22a070-9091-4986-9bee-25cbc7482f98)

Am I missing something here?

**Comment by jd1378** [comment]
@madebyfabian  are you using explicit import option that was newly added? 
if so you need to provide the import query: 
```
import IconArrowRight from '@/assets/images/icons/arrowRight.svg?componentext'
```
let me know if my assumption is incorrect

**Comment by jd1378** [comment]
I have updated to latest version and my config does recognize `svgo.customComponent` option

**Comment by madebyfabian** [comment]
@jd1378 Sorry for the late response. I changed every import to `?componentext` and now everything works. Interestingly, typings now also work. Thanks again for your work!
