### ISSUE TITLE
solution to override stroke | color

### ISSUE THREAD

**Issue by nort3x** [cpsoinos/nuxt-svgo#156]
Hi,

Suppose I have an SVG like this:

```html
<svg fill="none" viewBox="0 0 24 24" width="1.5rem">
  <g stroke="#F95CA3" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5">
    <!-- ... -->
  </g>
</svg>
```
I want to change the color of the svg, but it seems like I can't do it with any inline styles or attributes (please correct me if I'm wrong). However, I can create a class in the style and select all sub-elements to override their stroke with the desired color. The issue is that I have to set the style from scoped to global, and I think it's a problem.

```vue
<template>
  <Teacher class="colored" />
</template>

<script setup lang="ts">
import Teacher from "./assets/teacher.svg"
</script>

<!-- Can't use scoped -->
<style>
.colored * {
  stroke: red !important;
}
</style>
```

It's not a good developer experience (DX) to use styles for coloring, let alone having classes being global! Also, please note that I'm new to frontend development.

**Comment by jd1378** [comment]
well why not edit your svg and use `currentColor` wherever you need ? like `stroke="currentColor"`

**Comment by nort3x** [comment]
magnificent!
just for the record if you are dealing with huge number of icons use this
```bash
sed -i 's/#\([0-9A-Fa-f]\{6\}\)/currentColor/g' *
```

**Comment by lefhl** [comment]
Hello! It's working if you have quite simple icon. For example you have multicolored icon and you need to change color of some parts on hover. Also, `currentColor` is not the best solution because sometimes it's unlikely you have the same color for text and for the icon and you have to every single time to ajust icon's `currentColor` to the color from design. It would be much better to have an opportunity to reach svg content from css.

**Comment by lefhl** [comment]
But I found a workaround.
```
.icon[class*="bell-icon"] {
  &:hover {
    animation: bell .4s ;
    [class*="bell-active"] {
      fill: var(--btn-primary-color);
    }
  }
}
```
bell-icon - this is a part of class name of svg element. bell-active - the same for the svg inside element.

In HTML it looks like:
`<svg data-v-bc00cfcb="" xmlns="http://www.w3.org/2000/svg" fill="none" class="i300807355__bell-icon icon" viewBox="0 0 
  24 24" style="--9252cce3-finalWidth: 24px; --9252cce3-finalHeight: 24px;">
  <circle cx="12.05" cy="9.9" r="7" fill="#A7A7A7" class="i300807355__bell-active"></circle>
  <circle cx="20.45" cy="18.3" r="1.4" fill="#A7A7A7" class="i300807355__bell-active"></circle>
  <circle cx="3.65" cy="18.3" r="1.4" fill="#A7A7A7" class="i300807355__bell-active"></circle>
  <circle cx="12.05" cy="2.9" r="1.4" fill="#A7A7A7" class="i300807355__bell-active"></circle>
  <path fill="#8E8E8E" d="M12.05 22.5a2.8 2.8 0 0 0 2.8-2.8h-5.6a2.8 2.8 0 0 0 2.8 2.8Z" class="i300807355__bell-active"> 
  </path>
  <path fill="#A7A7A7" d="M20.45 19.7H3.65v-2.8c.467-1.108 1.4-4.13 1.4-7.35h14c0 4.48.934 6.767 1.4 7.35v2.8Z" 
   class="i300807355__bell-active"></path>
   <path fill="#D9D9D9" d="M20.45 16.9H3.65c.42-.98.759-2.508.875-3.15H19.4c.28 1.4.817 2.683 1.05 3.15Z"></path>
</svg>`

**Comment by jd1378** [comment]
I thought about it back then and I reached conclusion that it's better to be done for individual icons manually, because there's only one "currentColor" in css (I mean no similar keyword) and achieving same kind of DX for stroke is hard imo

**Comment by mrleblanc101** [comment]
Why not do it with svgo ?
```
// svgo.config.js
module.exports = {
    plugins: [
        {
            name: 'removeAttrs',
            params: {
                attrs: '(fill|stroke)',
            },
        },
    ],
};
```

**Comment by jd1378** [comment]
because it depends on the SVG and doing that can break it

**Comment by mrleblanc101** [comment]
@jd1378 It should only be used for icons, if your SVG is not an icon, you should load it using this library or you should use the ?skipsvgo

**Comment by jd1378** [comment]
well you do in fact get benefits by importing using svgo for SVGs in general, but even in icons it does not work perfectly 
some icons are made using strokes, some fills, removing both for all icons does not end very well, for me at least

**Comment by mrleblanc101** [comment]
@jd1378 Well, you neee to export the icon properly. There is no reason to mix stroke and fill.
