### ISSUE TITLE
Feature request: Enable configuring the different icon prefix

### ISSUE THREAD

**Issue by lukasaric** [cpsoinos/nuxt-svgo#165]
Currently there's no way to change the `icon` prefix (`Svgo` prefix is fixed).
The proposal is to add the `prefix` option within the  svgo nuxt config so that we can have the desired prefix.

@cpsoinos @jd1378

**Comment by jd1378** [comment]
Hi
Sure, we have customized nearly everything, I can't see why not
will work on it when I have time

**Comment by lukasaric** [comment]
> @lukasaric let me know if there's any issue :)

Works like a charm! 🎉
