### ISSUE TITLE
Conflict with module nuxt-icon

### ISSUE THREAD

**Issue by hhhhaaarry** [cpsoinos/nuxt-svgo#179]
I'm using nuxt-icon to manage my icons, but i'm using nuxt-svgo to import custom svgs (illustrations, not icons). The issue here is that is adding nuxt-icon and nuxt-icon--fill to my svg, breaking the fill color of all elements.

**Comment by hhhhaaarry** [comment]
I fixed it adding "filled" to the component template, this was on nuxt-icon documentation, buy i couldn't find it on svgo

**Comment by jd1378** [comment]
I saw it was already under [Component props](https://github.com/cpsoinos/nuxt-svgo#component-props)
