### ISSUE TITLE
How dynamically import in loop?

### ISSUE THREAD

**Issue by Ask1n** [cpsoinos/nuxt-svgo#191]
Hi, can I dynamically import icons by name in a loop?

**Comment by jd1378** [comment]
Hi
I didn't understand what do you mean exactly
but as long as `global` option of plugin is true, you should be able to load the icons dynamically without any problem

**Comment by Ask1n** [comment]
> Hi I didn't understand what do you mean exactly but as long as `global` option of plugin is `true`, you should be able to load the icons dynamically without any problem

I mean when I need to display different icons in a component depending on the data from the API. 

Like this

```vue
<Card
    v-for="item in data"
    :key="item.id"
  >
    <Icon :name="item.iconName" />
    {{ item.title }}
</Card>
```

**Comment by jd1378** [comment]
Hi
you have to treat the icons as components

I assume your svgo component icon name is "Icon", and your icon names are kebab case, and `global` option is set to true for nuxt-svgo (default is `true`):

```vue
<Card
    v-for="item in data"
    :key="item.id"
  >
    <component :is="`lazy-icon-${item.iconName}`" />
    {{ item.title }}
</Card>
```
though make sure to build the app and see if it still works on production, but that should do it

**Comment by Ask1n** [comment]
I disabled `global` in the project

Now I solved it this way, maybe there is a better solution
```vue
<script setup>
import IconOne from '~/assets/icons/one.svg'
import IconTwo from '~/assets/icons/two.svg'

const icons = {
  category1: IconOne,
  category2: IconTwo,
}
</script>

<Component :is="icons[item.iconName]" />
```

**Comment by jd1378** [comment]
well I don't think there is a better solution. the `global` option ensures each icon get it's own chunk and that you can load them dynamically in production from what I understand. so it cannot be done without that, because there isn't any guarantee which items are needed at any point in time. 

but, I use the same solution as you have mentioned, it works well when you have stuff that don't come from an API and doesn't change often

**Comment by jd1378** [comment]
as a bonus, you can import your icons like this for less verbosity:
```
import {IconOne, IconTwo} from #components"
```
