### ISSUE TITLE
Return the optimized SVG in string

### ISSUE THREAD

**Issue by josuelrocha** [cpsoinos/nuxt-svgo#193]
Hello @jd1378 @cpsoinos,

I'm in a situation where I'm working with Google Maps and I'm creating some custom buttons for the map and I need to do some things in vanilla.js, and one of them is to put an SVG inside a button, so I'm importing my SVG using the query `?raw`, and this is perfect, because I can use it in my button like `button.innerHTML = SVG`, the only problem with this is that when I use the query `?raw` the SVG returned to me in the form of a string does not is optimized, so I would like to ask if it would be possible to create another query, something like `?raw_optimized` / `?optimized_raw` or `?plain` that returns an optimized SVG string? I believe this is very useful for many people who, for some reason, need to work with some SVG directly.

Thanks.

**Comment by jd1378** [comment]
Hi
I'm sorry, but I'm a bit busy right now, so I can't implement it anytime soon

I can help merge PR if you are interested to contribute though

I think we can go with `raw_optimized`

**Comment by josuelrocha** [comment]
Hello, I added the feature and made a pull request #194 , could you check if everything is ok?
