### ISSUE TITLE
How would you go to disable CSS

### ISSUE THREAD

**Issue by mohdlatif** [cpsoinos/nuxt-svgo#199]
The default CSS

```
.nuxt-icon--fill, .nuxt-icon--fill * {
    fill: inherit;
}
```

is causing color issues to some of my SVGs. 

Is there any custom attribute or something else to disable CSS.

**Comment by mohdlatif** [comment]
I just created a new custom components and that solved it for me.

**Comment by jd1378** [comment]
or, you could change the default import to `component` instead of `componentext`, which would not wrap the your component anymore

btw, you could set "filled" prop on the original component and your original colors would have been used :)
