### ISSUE TITLE
when I use `customComponent`, I need svg name to add default class

### ISSUE THREAD

**Issue by Dante-dan** [cpsoinos/nuxt-svgo#200]
when I add a customComponent to replace `nuxt-icon.vue`, I need some original information to controll my component. But `componenttext` only transfer render to component, so I need transfer svg name to component

**Comment by jd1378** [comment]
Can I ask why ? like how do you plan to use the name ?

**Comment by Dante-dan** [comment]
I'll use `home-filled` and `home-outline` as well as `home-colorful` to represent monochrome filled icons, monochrome outlined icons, and two-colored icons. When using two-colored icons, I want the inner and outer layers to have different colors, so I'd like the default value for `filled` in all `*-colorful` icons to be `true`.

In other words, icons often have different states for the same icon used in different scenarios, and the icon names themselves follow certain conventions. 

Therefore, I need the icon names to calculate some default values for configurations.

**Comment by Dante-dan** [comment]
For example, designers might use a prefix like `m20-w22-home.svg` in the icon name to indicate constraints on the icon size.

In fact, when dealing with cross-team communication, icon names themselves convey a lot of information. This information is essential to be passed to the component runtime, thereby reducing communication costs.

**Comment by jd1378** [comment]
I understand, that's an interesting way to do it, thanks for explaining

**Comment by jd1378** [comment]
@Dante-dan sorry for the delay, I hope this works for you :)
