### ISSUE TITLE
[BUG REPORT] I found a fatal bug while using the svgo module

### ISSUE THREAD

**Issue by yongho0605** [cpsoinos/nuxt-svgo#204]
- OS: mac 14.1
- Browser: chrome latest
- Nuxt version: 3.8.1
- SVGO version: 3.7.0

## nuxt config
``` js
svgo: {
    componentPrefix: 'i-custom'
  },
```

## Problem

1. The `nuxt-icon` component is not getting the original color even though filled props is true. 

2. And even though we set the fontControlled props to false, we can still control it with font.

3. Despite not adding `defaultImport: 'component'` in nuxt.config , it renders as two components
```jsx 
<nuxt-icon icon="i-custom-object-3d" class="text-4xl" />
<i-custom-object-3d
  class="h-10 w-10 text-blue-300"
  :font-controlled="false"
/>
<i-custom-xbox class="h-10 w-10 text-red-400" />
```
### example image
![스크린샷 2023-12-06 오후 4 01 48](https://github.com/cpsoinos/nuxt-svgo/assets/127718221/60a1b8ed-cb17-4bba-bd20-ad55680564ac)

### original image
![스크린샷 2023-12-06 오후 3 52 22](https://github.com/cpsoinos/nuxt-svgo/assets/127718221/912a2948-d177-4d31-9c2a-c65805d17695)

![스크린샷 2023-12-06 오후 3 54 45](https://github.com/cpsoinos/nuxt-svgo/assets/127718221/b18a10c7-a977-4595-b6e5-adceb6868827)

**Comment by jd1378** [comment]
Hi

> Despite not adding defaultImport: 'component' in nuxt.config , it renders as two components

please clarify your issue, I am confused what is the problem exactly

please note that the default behavior is to load SVGs as nuxt-icon component. `defaultImport` allows you to change that behavior.

this is not a correct usage:

```vue
<nuxt-icon icon="i-custom-object-3d" class="text-4xl" />
```

please double check that svgo is not ruining your svg, as it sometimes does for my icons.

adding `filled` prop should use your original colors, there's probably some other issue. please note that svgo messes with IDs, so for example if you have a gradient fill, and it has an ID, chances are that you have another gradient with the same id in the dom already, so it won't work properly.

 > I wish we could configure the default for the "filled" prop in the nuxt config so I don't have to set :filled=true everywhere.

well you can always create your own component and set your desired defaults. the default component provided by nuxt-svgo is for common use case. if you have specific use case, it still offers enough customizability to let you do what you want.

**Comment by yongho0605** [comment]
I must have misunderstood the documentation, I apologize. But could you please write something in the documentation to help people understand it better? I don't think I understand the function of the option `defaultImport`, even though I've read the documentation several times. I'll read it one more time!

Also, I think it would be good to clarify about the `filled` props, where the ids in the DOM can overlap. 

Thanks for the answer!

**Comment by yongho0605** [comment]
> > Also, I think it would be good to clarify about the filled props, where the ids in the DOM can overlap.
> 
> well the problem with ids is not specific to nuxt-svgo, but svgo itself. it is not about the filled prop.
> 
> one potential solution, if vite supports it in future, is to optimize the SVGs and load their URL, so it can be used as an `<img />` tag, that would solve this issue for good, but last time I checked (on vite v4) it was not possible yet. this would help with SVGs that have a lot of color and you don't want to color based on the `currentColor`.
> 
> so if this issue keeps bothering you and you want to keep the svg's original colors, for now, I suggest optimizing your svgs using a service like [vecta.io/nano](https://vecta.io/nano), and load that as url (using `?url`), and pass it to an `img` src. the only downside is you cant use `currentColor` anymore.

oh, I exactely understood.

thanks for your comment and time
