### ISSUE TITLE
library is broken not working plz check it on my codesandbox

### ISSUE THREAD

**Issue by xalteropsx** [cpsoinos/nuxt-svgo#206]
nuxt new version causing problem on nuxt-svgo https://stackblitz.com/edit/nuxt-svgo-playground-r66bkh?file=nuxt.config.ts  //bugged  3.8.2 

![image](https://github.com/cpsoinos/nuxt-svgo/assets/103671642/2885b60c-13e8-43c3-a163-257b26974344)
previous nuxt version run this svg properly while newer version conflicting
u can compare to original https://stackblitz.com/edit/nuxt-svgo-playground?file=nuxt.config.ts  "nuxt": "3.0.0-rc.4"

https://discord.com/channels/473401852243869706/897487139888062506/1182722168921010226
here the video i have send this to nuxt discord

**Comment by jd1378** [comment]
I feel like you are using different nuxt-svgo versions as well

use `:font-controlled="false"` on your component and see if it resolves your issue.
if it does, then you need to read the readme again for the new usage
