### ISSUE TITLE
Cannot find module typescript error when importing queries

### ISSUE THREAD

**Issue by OversensitiveCat** [cpsoinos/nuxt-svgo#207]
Hello,

I'm trying to import a svg with the skipsvgo query, and I get this error :

Cannot find module '@/assets/icons/logo.svg?skipsvgo' or its corresponding type declarations. 

I already added a custom.d.ts file as explained in the documentation. All the queries are throwing this error except the 'raw'.

Am I missing something in the typescript configuration ?

Thanks a lot

**Comment by jd1378** [comment]
Hi

I have this problem myself and I'm not sure what's the solution

**Comment by jd1378** [comment]
the error does not prevent my project from working properly though, it's just an error in ide for me

**Comment by OversensitiveCat** [comment]
Yes, it's the same for me. It's just a bit annoying to see these mistakes all the time...

**Comment by jd1378** [comment]
found how to get it working:

create a `custom.d.ts` file (name does not matter) with these content:
```
declare module '*.svg' {
  import type {Component} from 'vue';
  const component: Component;
  export default component;
}
declare module '*.svg?skipsvgo' {
  import type {Component} from 'vue';
  const component: Component;
  export default component;
}
```

add it to your `tsconfig.json`:
```jsonc
{
  "extends": "./.nuxt/tsconfig.json",
  "files": ["custom.d.ts"] // <----------- add this line
}
```

**Comment by OversensitiveCat** [comment]
Amazing, thank you !
