### ISSUE TITLE
Folder Resolving is wrong

### ISSUE THREAD

**Issue by marvhock** [cpsoinos/nuxt-svgo#230]
I have following folders

icons/app
icons/app/appStore.svg
icons/app/playStore.svg

however the expected Icon Names do not work like:
<IconAppPlayStore />
<IconAppAppStore />

but:
<IconAppPlayStore />
<IconAppStore />

So it does not work consistent, as the latter IconAppStore does not present its folder in the name.
Is this a known Bug?

**Comment by jd1378** [comment]
Hi
The resolution is done by nuxt:
https://github.com/cpsoinos/nuxt-svgo/blob/23f19fc0e2e8803f57fe5748cad67c97fed1a0c2/src/module.ts#L89
