### ISSUE TITLE
Global config to disable font controlled on all component

### ISSUE THREAD

**Issue by misbahansori** [cpsoinos/nuxt-svgo#240]
HI, when I use this plugin, it automatically includes the `nuxt-icon` class in the SVG with default styling. If I want to avoid that class, I can disable it by setting `:font-controlled="false"`, but having to do this for every component is tedious. It'd be great to have a global option for this.

**Comment by jd1378** [comment]
well, you already can replace the component that is being used very easily by using the `customComponent` option

I understand the default settings is not for everyone but what you are asking is way easier to achieve by [copying the component this package provides](https://github.com/cpsoinos/nuxt-svgo/blob/main/src/runtime/components/nuxt-icon.vue) and editing it to suit your needs, then use it in `customComponent` option

**Comment by misbahansori** [comment]
Thanks for the response. Okay no problem, I will use the custom component for now.
