### ISSUE TITLE
`svgoConfig` options don't seem to be applied.

### ISSUE THREAD

**Issue by matthew-dean** [cpsoinos/nuxt-svgo#247]
I have nuxt-svgo importing SVGs, but it doesn't seem to transform anything with the `svgoConfig` section.

For example, please see this StackBlitz: https://stackblitz.com/edit/nuxt-svgo-playground-9mbztr?file=nuxt.config.ts - Height / width are not applied to the SVG.

**Comment by jd1378** [comment]
Hi
I cannot confirm:
![image](https://github.com/cpsoinos/nuxt-svgo/assets/6196533/63c7166c-4dff-409b-b63d-2ba0a7608863)

I have updated nuxt to latest version before testing though as it was saying upgrade required.

**Comment by jd1378** [comment]
Thanks for the detailed reaponse
I'm glad it's working for you
