### ISSUE TITLE
Icon dont starts with default svg size

### ISSUE THREAD

**Issue by mitraecp** [cpsoinos/nuxt-svgo#273]
```
<svgo-social-discord
					color="var(--grey-700)"
					class="w-[16px] h-[16px]"
				/>
```

I import an icon, but the sizes dont keep values on viewbox or original svg file, i need to set on every icon the sizes?

**Comment by jd1378** [comment]
the size is controlled by font size by default
to disable font control, use `:font-controlled="false"`

the default svgo configuration is mentioned in the readme, you can change the behavior if you need to
