### ISSUE TITLE
For images in the /public dir, I get warn in the console.

### ISSUE THREAD

**Issue by leo91000** [cpsoinos/nuxt-svgo#284]
Hello,
When including a public image with this module in a vue component :

```html
<img src="/img/icone-pageplateforme-approcheludique.svg" alt="Approche ludique" width="55" height="55" class="h-10 w-10">
```

I get warnings : 
```
WARN
virtual:public?%2Fimg%2Ficone-pageplateforme-approcheludique.svg couldn't be loaded by vite-svg-loader, fallback to default loader
```

**Comment by jd1378** [comment]
I just want to point out Nuxt-Svgo cannot optimize SVGs this way
it only can optimize when they are loaded as components

I have made a fix to ignore this type of usage to prevent it from throwing warns
