### ISSUE TITLE
Inefficient Regular Expression Complexity in nth-check

### ISSUE THREAD

**Issue by OyewoleOyedeji** [cpsoinos/nuxt-svgo#53]
The latest possible version that can be installed is 1.0.2 because of the following conflicting dependency:

`nuxt-svgo@1.0.1 requires nth-check@^1.0.2 via a transitive dependency on css-select@2.1.0`

The earliest fixed version is 2.0.1.

Link to security alert [https://github.com/OyewoleOyedeji/discord-profiler/security/dependabot/14](https://github.com/OyewoleOyedeji/discord-profiler/security/dependabot/14)

**Comment by jd1378** [comment]
this should be solved since we don't depend on `vue-svg-loader` and webpack related ones directly (they are peer dependency now)
feel free to open another issue or comment here if issue remains with v2
