### ISSUE TITLE
Installing nuxt-svgo gives 5 high severity vulnerabilities

### ISSUE THREAD

**Issue by bootsmann1995** [cpsoinos/nuxt-svgo#57]
When installling nuxt-svgo -> npm returns 5 high serverity vunerabilities

npm audit log:

![image](https://user-images.githubusercontent.com/65391517/198024102-07faf47c-0915-40ee-80ca-cbd3acae8a1d.png)
![image](https://user-images.githubusercontent.com/65391517/198024133-40523e9e-c604-4ba5-8808-001b8f06b036.png)

**Comment by jd1378** [comment]
@cpsoinos also this ?

**Comment by jd1378** [comment]
this is no longer the case since we updated dependencies on v2
feel free to open another issue if it comes up again.
