### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by provok-it** [cpsoinos/nuxt-svgo#80]
### Reproduction
- Install Nuxt 3.1.0
- Install Nuxt-svgo

[Reproduction link](https://stackblitz.com/edit/github-etab9x?file=nuxt.config.ts)

**Comment by jimmiejackson** [comment]
Any update on this? I'm facing the same issue.

**Comment by josuelrocha** [comment]
I have the same problem, Nuxt 3.3.3.

**Comment by provok-it** [comment]
Poke @cpsoinos

**Comment by cpsoinos** [comment]
Hi @provok-it - sorry I haven't kept up with issues in this repo. I no longer use Vue or Nuxt regularly (my company uses React and Next.js). I'll try to take a look at this this evening.

**Comment by provok-it** [comment]
Thank you for your quick response @cpsoinos.

Could you talk with Atinux or Pi0 at Nuxt to help them point out a new maintainer in this case?

**Comment by cpsoinos** [comment]
Hey @provok-it, this appears to have been an upstream issue with Nuxt, reported here: https://github.com/nuxt/nuxt/issues/13897

When using the latest version of `nuxt` (at present, `3.4.2`) with `nuxt-svgo@1.2.1`, the problem disappears: https://stackblitz.com/edit/nuxt-starter-eq92w1?file=nuxt.config.ts

**Comment by gbyesiltas** [comment]
I get this error with nuxt `3.7.4` and `nuxt-svgo@3.5.6` :,(

**Comment by gbyesiltas** [comment]
Yeah I currently only have this issue with this module though we are using about 7-8 modules :/

**Comment by jd1378** [comment]
Hi @lovkyndig  @gbyesiltas 
sorry for the late response

according to [this comment](https://github.com/nuxt/nuxt/issues/13897#issuecomment-1708989100) by [danielroe](https://github.com/danielroe), it seems this is an issue with "multiple versions of nuxt/schema or kit installed"

can you upgrade your nuxt, or maybe delete your lock file and try installing packages again and see if it resolves the issue ?

**Comment by lovkyndig** [comment]
Thanks for your advice! 
I have confirmed that the issue is only existing in my windows machine. If I remove the
// @ts-ignore
in front of the first error in nuxt.config, before deploying it on vercel, it's working fine on internet.
But in my local development, I need `// @ts-ignore`, else it will not _build_, _dev_ or anything.

I have no `nuxt/schema`, but I have `@nuxt/kit`installed: I will try to remove _@nuxt/kit_. 
Thanks @jd1378

**Comment by lovkyndig** [comment]
Yippi! 
That was the thing!
Removing `@nuxt/kit`and everything is working fine :)
Thank you so much @jd1378

**Comment by jd1378** [comment]
I'm glad the fix was simple
