### ISSUE TITLE
How to bypass SVGO for certain SVGs?

### ISSUE THREAD

**Issue by drewbaker** [cpsoinos/nuxt-svgo#85]
I don't see a way to bypass SVGO for certain SVGs? For example, I have some SVGs that are animated and require some IDs not to be removed. 

It would be great if I could do this:

```
import IconHome from '~/assets/icon-home.svg?svgno'
```

And it would then skip SVGO and just give me the raw SVG, thus `svg no` LOL.

I haven't tried it yet, but I'd expect the vite-svg-loader options like `?url` should work too.

**Comment by drewbaker** [comment]
It seems that you could change the webpack loaders here:
https://github.com/cpsoinos/nuxt-svgo/blob/main/src/module.ts#L52-L65

To use query params to determine the different loader options. We do it for Nuxt2 SVGs here:
https://github.com/funkhaus/fuxt/blob/master/nuxt.config.js#L153

I don't know how to do a similar thing in Vite...

**Comment by riddla** [comment]
@drewbaker: as this plugin uses https://github.com/jpkleemans/vite-svg-loader under the hood – does the [`skipsvgo`  import parameter](https://github.com/jpkleemans/vite-svg-loader#skip-svgo-for-a-single-file) work for you?

**Comment by jd1378** [comment]
I believe `skipsvgo` import parameter mentioned by riddla does what OP asked for, so I'm closing this issue
feel free to open another issue if anything comes up or this doesn't work as expected
