### ISSUE TITLE
Is it possible to change defined ids for every time an svg is rendered?

### ISSUE THREAD

**Issue by jd1378** [cpsoinos/nuxt-svgo#88]
right now when loading a svg, the first time its loaded the gradients defined in it works fine
but when you load the same svg for the second time, it no longer renders correctly, as ids clash
I was wondering if we could prefix an incremental number to the svg ids used inside it every time its loaded

**Comment by cpsoinos** [comment]
Hi @jd1378 - thanks for reporting this. I'll try to take a look at it this evening.

**Comment by jd1378** [comment]
hi 
I have opened an issue here as well, since I thought it might be an upstream issue:
https://github.com/jpkleemans/vite-svg-loader/issues/98

**Comment by fahdlaabi** [comment]
For now, you can just add this in plugins:

```js
svgo: {
  svgoConfig: {
    multipass: true,
    plugins: [
      {
        name: "preset-default",
        params: {
          overrides: {
            cleanupIds: false,
          },
        },
      },
    ],
  },
},
```

**Comment by jd1378** [comment]
How is it going to help the problem ? Its gonna have the same result

**Comment by jd1378** [comment]
well with moving vite plugin inside, It may be possible, but without digging deep into svgo it seems to be hard to do
I have lost interest in this, because I simply stopped using svgs with ids, or switched the gradients with similar looking fill colors
