### ISSUE TITLE
Configuration to set path for automatic import of icons.

### ISSUE THREAD

**Issue by josuelrocha** [cpsoinos/nuxt-svgo#96]
I would like to suggest an idea. The idea is to add a configuration to set the path of the automatic import icons, which is currently in static mode for `assets/icons/`, but this generates a problem, for example, in the project I'm working on, this folder has hundreds of icons, however not all are currently being used, but they may be used in the future. The problem is that because of `import.meta.glob`, it's including all the svg icons in my production build, even the svg icons I'm not using, unnecessarily making the project bigger. So my suggestion is to add a path setting where the icons will be imported automatically, for example, in my project I could set it to `assets/icons/auto/`, because I know that all the svg icons that I put inside that folder, will go to the production build.

pull #91 

@cpsoinos @jd1378

**Comment by jd1378** [comment]
sounds reasonable, I wanted to do it at some point, but how can we do it exactly? I haven't give it enough thoughts

also, I was curious about this as well, since the vite docs mentions about this being tree-shakable, while it includes all icons,
so I am just asking again to confirm, you have seen the increase in size in a production build ?

**Comment by jd1378** [comment]
I can confirm this
but I don't know of a way to pass it as a config
[globe import](https://vitejs.dev/guide/features.html#glob-import) mentions that it only support literals

**Comment by josuelrocha** [comment]
Just confirming your question. Yes I checked that, all the icons that are inside the folder are going to production and increasing the build size.

There really is this limitation of dynamic import with Glob import of working only with template literals, at the moment I don't have an idea for that, I would have to think a little. I believe that at least for now, the best would really be just to change the path of the default folder as mentioned by you.

**Comment by jd1378** [comment]
I just got an idea to ditch the globe import and use a different way entirely to support the true dynamic tree shakable import nuxt offers, but I have to play around with the idea to see if it actually works

will post an update when I test it

**Comment by jd1378** [comment]
well the first part of the idea is working

I managed to get it to load icons the nuxt way, like this:

```
addComponentsDir({
        path: await resolvePath(options.iconDirPath),
        global: true,
        extensions: ['svg'],
        prefix: 'svgo',
      })
```

which:
1. makes it tree shakable
2. makes is so we can set the dir path we want
3. makes it possible to disable it using an option as well

**Comment by jd1378** [comment]
the only thing we lack now is the control the component was providing us

now it directly uses what it has been using, the vite plugin, which I still have little idea about it

so If I figure the next step, which is to use the vite's plugin's component and pass it to our component, then we have a very good tree shakable component out of it

**Comment by jd1378** [comment]
okay I think the only proper way to control it as a component is to edit the svg loader plugin for vite
given that the source for the plugin is actually quite small, we can probably copy it over and modify the source to apply our changes

this time around we can make everything optional

I'll make a PR for it

**Comment by cpsoinos** [comment]
Awesome, thanks @jd1378

**Comment by josuelrocha** [comment]
You are doing an excellent job @jd1378

**Comment by jd1378** [comment]
I'm almost done, just cleaning up readme for the new usage

**Comment by jd1378** [comment]
I'm going to rest for a while, let me know if I need to do anything to get this released faster @cpsoinos

**Comment by jd1378** [comment]
Also I propose to add this config by default to ensure things are working fine out of the box:
```
svgo: {
    svgoConfig: {
      plugins: [
        {
          name: 'preset-default',
          params: {
            overrides: {
              removeViewBox: false,
            },
          },
        },
        'removeDimensions',
        'prefixIds',
      ],
    },
  },
  ```

**Comment by cpsoinos** [comment]
> Also I propose to add this config by default to ensure things are working fine out of the box:
> 
> ```
> svgo: {
>     svgoConfig: {
>       plugins: [
>         {
>           name: 'preset-default',
>           params: {
>             overrides: {
>               removeViewBox: false,
>             },
>           },
>         },
>         'removeDimensions',
>         'prefixIds',
>       ],
>     },
>   },
> ```

I like the suggestion of disabling `removeViewBox` and enabling `removeDimensions`, but can you explain your thoughts behind enabling `prefixIds` by default? I don't think we should be changing the IDs within a user's SVG by default. A user can always enable this on their own if they want.

**Comment by jd1378** [comment]
okay, fair

the idea is ids clash very fast ,with only 2 svgs that have styles with ids, like gradiants

so I'll add the  suggestion, without the `prefixIds`
